/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  airway_accounts_detail: () => import("@/views/airway/accounts/detail/index.vue"),
  airway_accounts: () => import("@/views/airway/accounts/index.vue"),
  airway_accounts_new: () => import("@/views/airway/accounts/new/index.vue"),
  "airway_ad-permissions": () => import("@/views/airway/ad-permissions/index.vue"),
  airway_approval_apply: () => import("@/views/airway/approval/apply/index.vue"),
  airway_approval_center: () => import("@/views/airway/approval/center/index.vue"),
  airway_approval_detail: () => import("@/views/airway/approval/detail/index.vue"),
  airway_approval_fill: () => import("@/views/airway/approval/fill/index.vue"),
  airway_approval_templates: () => import("@/views/airway/approval/templates/index.vue"),
  airway_assets_detail: () => import("@/views/airway/assets/detail/index.vue"),
  airway_assets: () => import("@/views/airway/assets/index.vue"),
  airway_assets_intake: () => import("@/views/airway/assets/intake/index.vue"),
  airway_assets_new: () => import("@/views/airway/assets/new/index.vue"),
  airway_dashboard: () => import("@/views/airway/dashboard/index.vue"),
  airway_departments: () => import("@/views/airway/departments/index.vue"),
  airway_employee_import: () => import("@/views/airway/employee_import/index.vue"),
  airway_employees: () => import("@/views/airway/employees/index.vue"),
  airway_forms_apply: () => import("@/views/airway/forms/apply/index.vue"),
  airway_forms_center: () => import("@/views/airway/forms/center/index.vue"),
  airway_forms_data: () => import("@/views/airway/forms/data/index.vue"),
  airway_forms_designer_edit: () => import("@/views/airway/forms/designer/edit/index.vue"),
  airway_forms_designer: () => import("@/views/airway/forms/designer/index.vue"),
  airway_forms_detail: () => import("@/views/airway/forms/detail/index.vue"),
  airway_forms: () => import("@/views/airway/forms/index.vue"),
  airway_forms_permissions: () => import("@/views/airway/forms/permissions/index.vue"),
  airway_layout: () => import("@/views/airway/layout/index.vue"),
  airway_permissions: () => import("@/views/airway/permissions/index.vue"),
  airway_portal: () => import("@/views/airway/portal/index.vue"),
  airway_profile: () => import("@/views/airway/profile/index.vue"),
  airway_test: () => import("@/views/airway/test/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
