/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'airway',
    path: '/airway',
    component: 'layout.base',
    meta: {
      title: 'airway',
      i18nKey: 'route.airway'
    },
    children: [
      {
        name: 'airway_accounts',
        path: '/airway/accounts',
        meta: {
          title: 'airway_accounts',
          i18nKey: 'route.airway_accounts'
        },
        children: [
          {
            name: 'airway_accounts_detail',
            path: '/airway/accounts/detail',
            component: 'view.airway_accounts_detail',
            meta: {
              title: 'airway_accounts_detail',
              i18nKey: 'route.airway_accounts_detail'
            }
          },
          {
            name: 'airway_accounts_new',
            path: '/airway/accounts/new',
            component: 'view.airway_accounts_new',
            meta: {
              title: 'airway_accounts_new',
              i18nKey: 'route.airway_accounts_new'
            }
          }
        ]
      },
      {
        name: 'airway_ad-permissions',
        path: '/airway/ad-permissions',
        component: 'view.airway_ad-permissions',
        meta: {
          title: 'airway_ad-permissions',
          i18nKey: 'route.airway_ad-permissions'
        }
      },
      {
        name: 'airway_approval',
        path: '/airway/approval',
        meta: {
          title: 'airway_approval',
          i18nKey: 'route.airway_approval'
        },
        children: [
          {
            name: 'airway_approval_apply',
            path: '/airway/approval/apply',
            component: 'view.airway_approval_apply',
            meta: {
              title: 'airway_approval_apply',
              i18nKey: 'route.airway_approval_apply'
            }
          },
          {
            name: 'airway_approval_center',
            path: '/airway/approval/center',
            component: 'view.airway_approval_center',
            meta: {
              title: 'airway_approval_center',
              i18nKey: 'route.airway_approval_center'
            }
          },
          {
            name: 'airway_approval_detail',
            path: '/airway/approval/detail',
            component: 'view.airway_approval_detail',
            meta: {
              title: 'airway_approval_detail',
              i18nKey: 'route.airway_approval_detail'
            }
          },
          {
            name: 'airway_approval_fill',
            path: '/airway/approval/fill',
            component: 'view.airway_approval_fill',
            meta: {
              title: 'airway_approval_fill',
              i18nKey: 'route.airway_approval_fill'
            }
          },
          {
            name: 'airway_approval_templates',
            path: '/airway/approval/templates',
            component: 'view.airway_approval_templates',
            meta: {
              title: 'airway_approval_templates',
              i18nKey: 'route.airway_approval_templates'
            }
          }
        ]
      },
      {
        name: 'airway_assets',
        path: '/airway/assets',
        component: 'view.airway_assets',
        meta: {
          title: 'airway_assets',
          i18nKey: 'route.airway_assets'
        },
        children: [
          {
            name: 'airway_assets_detail',
            path: '/airway/assets/detail',
            component: 'view.airway_assets_detail',
            meta: {
              title: 'airway_assets_detail',
              i18nKey: 'route.airway_assets_detail'
            }
          },
          {
            name: 'airway_assets_intake',
            path: '/airway/assets/intake',
            component: 'view.airway_assets_intake',
            meta: {
              title: 'airway_assets_intake',
              i18nKey: 'route.airway_assets_intake'
            }
          },
          {
            name: 'airway_assets_new',
            path: '/airway/assets/new',
            component: 'view.airway_assets_new',
            meta: {
              title: 'airway_assets_new',
              i18nKey: 'route.airway_assets_new'
            }
          }
        ]
      },
      {
        name: 'airway_dashboard',
        path: '/airway/dashboard',
        component: 'view.airway_dashboard',
        meta: {
          title: 'airway_dashboard',
          i18nKey: 'route.airway_dashboard'
        }
      },
      {
        name: 'airway_departments',
        path: '/airway/departments',
        component: 'view.airway_departments',
        meta: {
          title: 'airway_departments',
          i18nKey: 'route.airway_departments'
        }
      },
      {
        name: 'airway_employee',
        path: '/airway/employee',
        meta: {
          title: 'airway_employee',
          i18nKey: 'route.airway_employee'
        },
        children: [
          {
            name: 'airway_employee_import',
            path: '/airway/employee/import',
            component: 'view.airway_employee_import',
            meta: {
              title: 'airway_employee_import',
              i18nKey: 'route.airway_employee_import'
            }
          }
        ]
      },
      {
        name: 'airway_employees',
        path: '/airway/employees',
        component: 'view.airway_employees',
        meta: {
          title: 'airway_employees',
          i18nKey: 'route.airway_employees'
        }
      },
      {
        name: 'airway_forms',
        path: '/airway/forms',
        component: 'view.airway_forms',
        meta: {
          title: 'airway_forms',
          i18nKey: 'route.airway_forms'
        },
        children: [
          {
            name: 'airway_forms_apply',
            path: '/airway/forms/apply',
            component: 'view.airway_forms_apply',
            meta: {
              title: 'airway_forms_apply',
              i18nKey: 'route.airway_forms_apply'
            }
          },
          {
            name: 'airway_forms_center',
            path: '/airway/forms/center',
            component: 'view.airway_forms_center',
            meta: {
              title: 'airway_forms_center',
              i18nKey: 'route.airway_forms_center'
            }
          },
          {
            name: 'airway_forms_data',
            path: '/airway/forms/data',
            component: 'view.airway_forms_data',
            meta: {
              title: 'airway_forms_data',
              i18nKey: 'route.airway_forms_data'
            }
          },
          {
            name: 'airway_forms_designer',
            path: '/airway/forms/designer',
            component: 'view.airway_forms_designer',
            meta: {
              title: 'airway_forms_designer',
              i18nKey: 'route.airway_forms_designer'
            },
            children: [
              {
                name: 'airway_forms_designer_edit',
                path: '/airway/forms/designer/edit',
                component: 'view.airway_forms_designer_edit',
                meta: {
                  title: 'airway_forms_designer_edit',
                  i18nKey: 'route.airway_forms_designer_edit'
                }
              }
            ]
          },
          {
            name: 'airway_forms_detail',
            path: '/airway/forms/detail',
            component: 'view.airway_forms_detail',
            meta: {
              title: 'airway_forms_detail',
              i18nKey: 'route.airway_forms_detail'
            }
          },
          {
            name: 'airway_forms_permissions',
            path: '/airway/forms/permissions',
            component: 'view.airway_forms_permissions',
            meta: {
              title: 'airway_forms_permissions',
              i18nKey: 'route.airway_forms_permissions'
            }
          }
        ]
      },
      {
        name: 'airway_layout',
        path: '/airway/layout',
        component: 'view.airway_layout',
        meta: {
          title: 'airway_layout',
          i18nKey: 'route.airway_layout'
        }
      },
      {
        name: 'airway_permissions',
        path: '/airway/permissions',
        component: 'view.airway_permissions',
        meta: {
          title: 'airway_permissions',
          i18nKey: 'route.airway_permissions'
        }
      },
      {
        name: 'airway_portal',
        path: '/airway/portal',
        component: 'view.airway_portal',
        meta: {
          title: 'airway_portal',
          i18nKey: 'route.airway_portal'
        }
      },
      {
        name: 'airway_profile',
        path: '/airway/profile',
        component: 'view.airway_profile',
        meta: {
          title: 'airway_profile',
          i18nKey: 'route.airway_profile'
        }
      },
      {
        name: 'airway_test',
        path: '/airway/test',
        component: 'view.airway_test',
        meta: {
          title: 'airway_test',
          i18nKey: 'route.airway_test'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
